version: '3.9'

services:

  cellenium:
    build:
      context: .
    env_file:
      - '.env'
    volumes:
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}
    restart: on-failure

  test_1:
    extends:
      service: cellenium
    command: >
      bash -c "pytest ./tests/test_1 -n ${PARALLEL} --alluredir=allure-results"

#  test_2:
#    extends:
#      service: cellenium
#    command: >
#      bash -c "pytest ./tests/test_2 -n ${PARALLEL} --alluredir=allure-results"
#
#  test_3:
#    extends:
#      service: cellenium
#    command: >
#      bash -c "pytest ./tests/test_3 -n ${PARALLEL} --alluredir=allure-results"

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ${PWD}/allure-results:/allure-results
      - ${PWD}/allure-reports:/cellenium/default-reports
    ports:
      - "4040:4040"
    healthcheck:
      test: ["CMD-SHELL", "python --version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: '2'
    restart: on-failure
    depends_on:
      test_1:
        condition: service_completed_successfully
#      test_2:
#        condition: service_completed_successfully
    command: >
       bash -c "allure generate allure-results --clean -o allure-reports && allure serve"

volumes:
  shared:
